# Generated by Django 3.2.7 on 2021-09-29 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_server', '0002_OAuth_model_overide'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillcategories',
            name='skill',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api_server.skill'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skillcategories',
            name='skillCategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api_server.skillcategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skillsets',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api_server.employee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skillsets',
            name='skill',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api_server.skill'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accesstoken',
            name='cqrs_revision',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='accesstoken',
            name='cqrs_updated',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='application',
            name='cqrs_revision',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='application',
            name='cqrs_updated',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='cqrs_revision',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='cqrs_updated',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='grant',
            name='code_challenge_method',
            field=models.CharField(blank=True, choices=[('plain', 'plain'), ('S256', 'S256')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='grant',
            name='cqrs_revision',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='grant',
            name='cqrs_updated',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='idtoken',
            name='cqrs_revision',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='idtoken',
            name='cqrs_updated',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='refreshtoken',
            name='cqrs_revision',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='refreshtoken',
            name='cqrs_updated',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='skill',
            name='cqrs_revision',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='skill',
            name='cqrs_updated',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='skill',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='skillcategories',
            name='cqrs_revision',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='skillcategories',
            name='cqrs_updated',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='skillcategories',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='skillcategory',
            name='cqrs_revision',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='skillcategory',
            name='cqrs_updated',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='skillcategory',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='skillsets',
            name='cqrs_revision',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='skillsets',
            name='cqrs_updated',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='skillsets',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
