# Generated by Django 3.2.7 on 2021-09-29 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_server', '0002_OAuth_model_overide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='skillset',
            field=models.ManyToManyField(through='api_server.SkillSets', to='api_server.Skill'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='categories',
            field=models.ManyToManyField(through='api_server.SkillCategories', to='api_server.SkillCategory'),
        ),
    ]
