# Generated by Django 3.2.7 on 2021-10-01 15:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_server', '0003_auto_20210929_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='hiring_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
