# Generated by Django 3.2.7 on 2021-09-27 08:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('soft_skill', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('name', 'soft_skill')},
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=500)),
                ('categories', models.ManyToManyField(to='api_server.SkillCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('hiring_date', models.DateTimeField(default=datetime.datetime.now)),
                ('photo', models.ImageField(upload_to='employees')),
                ('skillset', models.ManyToManyField(to='api_server.Skill')),
            ],
            options={
                'unique_together': {('name', 'surname', 'hiring_date')},
            },
        ),
    ]
